### ISSUE TITLE
Nancy latest version

### ISSUE THREAD

**Issue by sabven** [horsdal/microservices-in-dotnetcore#2]
Can you please let me know which version of Nancy I need to install. When I install the latest I get the error Package Nancy 1.4.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Nancy 1.4.3 supports: net40 (.NETFramework,Version=v4.0).

**Comment by trevjacobson** [comment]
You need to add Nancy 2.0.0-clinteastwood to your csproj file which targets .net core. The nancy package you added  targets the .Net 4.0 framework

**Comment by horsdal** [comment]
You can take a look at the `.csproj` files in the `2017-05` branch. They use Nancy `2.0.0-clinteastwood`  (which is sligtly newer than `barneyrubble`)
