### ISSUE TITLE
MicroserviceNet.Platform unable to resolve for .NetCoreApp V1.1

### ISSUE THREAD

**Issue by trevjacobson** [horsdal/microservices-in-dotnetcore#3]
I've gotten to the end of the book and was going to try running the chapter 12 project which references the project in chapter 11 for the OWIN middleware. When opening the chapter 12 project and modifying file locations to fit the local location for chapter 11 MicroserviceNET.Platform.csproj I receive the error

Unable to resolve 'C:\Users\trevor.jacobson\Documents\Visual Studio 2017\Projects\microservices-in-dotnetcore\src\Chapter11\MicroserviceNET.Platform\MicroserviceNET.Platform.csproj' for '.NETCoreApp,Version=v1.1'.	

I believe its saying that the platform project files aren't compatible with .NetCoreApp V1.1. I'm not sure what other modifications have to be made to either project but any insight into this issue would be appreciated.

**Comment by horsdal** [comment]
Does it say which platform `MicroserviceNET.Platform` could be resolved for or is that the whole error message?

**Comment by trevjacobson** [comment]
That's the whole error message. I clone the repository then checkout the 2017-05 branch and upon loading the solution I have 8 errors;
 4 are this with variation for file location:

Unable to resolve 'C:\Users\trevor.jacobson\Documents\Visual Studio 2017\Projects\microservices-in-dotnetcore\src\Chapter11\MicroserivceNET.Auth\MicroserivceNET.Auth.csproj' for '.NETCoreApp,Version=v1.1'.				

and 4 are this with variation for project location:

Unexpected dependency 'C:\Users\trevor.jacobson\Documents\Visual Studio 2017\Projects\microservices-in-dotnetcore\src\Chapter11\MicroserivceNET.Auth\MicroserivceNET.Auth.csproj' with no version number.	ShoppingCart	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResoluti	
If i run the powershell script the separate .exe programs open up and have the same error messages

**Comment by horsdal** [comment]
can you build the platform in the chapter 11 folder?
