### ISSUE TITLE
When will Chap04 converted to new .csproj? (would like to use dotnet build/run CLI)

### ISSUE THREAD

**Issue by alturium** [horsdal/microservices-in-dotnetcore#4]
Any luck on updating Chap04 to the new csproj  for use with the dotnet-cli? (on the 2017-05 branch)  There are also other projects that have not been updated.  I suspect that the conversion has issues.

The Chap04 code has not been updated for the new .csproj, and did try upgrade using "dotnet migrate" but encountered lots of issues, so I gave up trying to figure out how to get "dotnet build" work with "net461" as the targetframework. 

I was hoping that some brave soul would know how to get this to work for the dotnet-cli.  I have not tried using Vs2015 or VS2017 to build this project.

Thanks

**Comment by horsdal** [comment]
Oops seems both ch04 and ch03 are missing. I'll get those converted too of course. Sorry for the inconvenience and thanks for reporting.

**Comment by horsdal** [comment]
The branch should now have a ported version of ch04. Ch03 contains no code, so nothing to port.
Again, sorry for missing ch04.
